os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.11.3"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.11.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - yarn install
script:
  - chmod +x mvnw
  - ./mvnw -q clean test
  - yarn test
  - docker-compose -f src/main/docker/keycloak.yml up -d
  - docker-compose -f src/main/docker/postgresql.yml up -d
  - ./mvnw -q &
  - bootPid=$!
  - sleep 30s
  - yarn e2e
  - kill $bootPid
  - ./mvnw -q package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
