version: '2'
services:
    ojo-app:
        image: ojo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ojo-mysql:3306/ojo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ojo-mysql:
        extends:
            file: mysql.yml
            service: ojo-mysql
